/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./RaffleContract.types";
import * as _1 from "./RaffleContract.client";
import * as _2 from "./RaffleContract.message-composer";
export namespace contracts {
  export const RaffleContract = {
    ..._0,
    ..._1,
    ..._2
  };
}